# Generated by Django 6.0.1 on 2026-01-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderation_reason',
            field=models.TextField(blank=True, verbose_name='Причина модерации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонён')], default='draft', max_length=15, verbose_name='Статус'),
        ),
    ]
