# Generated by Django 6.0.1 on 2026-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_moderation_reason_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Краткое описание'),
        ),
    ]
