# Generated by Django 6.0.1 on 2026-01-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation_reason',
            field=models.TextField(blank=True, verbose_name='Причина модерации'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонён')], default='draft', max_length=15, verbose_name='Статус'),
        ),
    ]
