# Generated by Django 6.0.1 on 2026-01-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_moderation_reason_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=15, verbose_name='Статус'),
        ),
    ]
