# Generated by Django 6.0.1 on 2026-01-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='context',
            new_name='content',
        ),
    ]
