# Generated by Django 6.0.1 on 2026-01-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_deleted_at_note_is_deleted_note_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_pinned', '-updated_at'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
